### ISSUE TITLE
breaks when used from a module

### ISSUE THREAD

**Issue by ashwanthkumar** [warmsea/node-rfr#1]
I have a node project "A", which uses rfr. Now I publish this module and use it another project "B". All the A's rfr now points to B's project root instead of its `./node_modules/A`. May be I am using it wrong. Any points how do I effectively use rfr when it is used within a module?

**Comment by warmsea** [comment]
Maybe make rfr a [**bundled dependency**](https://docs.npmjs.com/files/package.json#bundleddependencies) of module B could help.

It will pack rfr as a part of module B, so a separated copy is guaranteed.
